### ISSUE TITLE
docs unclear to follow

### ISSUE THREAD

**Issue by marekpetak** [AndersMalmgren/SignalR.EventAggregatorProxy#23]
HI there, I'm trying to use your library, but I cannot get my head arround the docs or the demos.
I did read through you blog, old bugs noNinjectDemo branch, but I am not able to follow your documentaion successfully. Is there a chance for more detailed wiki or tutorial?

I do have specific issue which is here http://stackoverflow.com/questions/33481538/signalr-eventaggregatorproxy-simple-example-issues

**Comment by AndersMalmgren** [comment]
Hi, glad you show interest in my library!
Please check your SO question, I have wrote an answer for you

**Comment by marekpetak** [comment]
Thank you! But the issue is still there ... I've updated SO.

**Comment by AndersMalmgren** [comment]
How did this go?

**Comment by marekpetak** [comment]
not well... I undersdand why there might be an issue with the SignalR setup, but I do not think this is the case. I'm thinking more that the issue is with my EventAgregator setup and its mapping to SignalR and its dependency resolver...
