### ISSUE TITLE
Possible multithread issue in EventProxy.cs - Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by andersthorsen** [AndersMalmgren/SignalR.EventAggregatorProxy#24]
I'm seeing this stack trace from time to time in the .NET Client

Error description: 
Error while subscribing to changes (SignalR)

Collection was modified; enumeration operation may not execute.

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare() 
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext() 
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) 
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) 
   at SignalR.EventAggregatorProxy.Client.EventAggregation.EventProxy`1.SendQueuedSubscriptions(Boolean reconnected)

**Comment by AndersMalmgren** [comment]
Nice find, will investigate, a bit much on my table right now. But will look at asap. I use the client in one real production client, have never stumble across a problem like this.

**Comment by AndersMalmgren** [comment]
Please test new version

**Comment by andersthorsen** [comment]
Thanks for the quick fix. I've had it running for a couple of days now and it seems to work fine.

**Comment by AndersMalmgren** [comment]
Cool, I can't understand that you run into this in production. I couldn't reproduce it with actual production code, I had to abstract the throttle logic and remove it in the test for the code to crash. 

I throttle each call to subscibe so if multiple calls comes in during 2 ticks on the system clock (32ms) it will be queued and sent together. You must get a new subscription exactly when the throttle logic is purging the queue, that is extremely unlikely to happen and should not be see often in production :) or do you subscribe very often for some reason?

**Comment by andersthorsen** [comment]
Not really.

The application has a few main views, some settings views  in addition to one class for master data that track notification from their server counterpart. 

The views are loaded asynchronously so if the user opens two at the same time this happened around 40% of the time. Not sure how they happened at the same time so often, but I guess it could have to do with how the task scheduler is implemented in .NET.

**Comment by AndersMalmgren** [comment]
Strange, oh well, good that we fixed code that should be thread safe. Thanks for finding it!
