### ISSUE TITLE
clarification required on local and remote publish

### ISSUE THREAD

**Issue by oising** [AndersMalmgren/SignalR.EventAggregatorProxy#25]
So, is it correct that the JS proxy can only subscribe to the remote aggregator's events, but cannot publish? I see you're calling a REST API to fire remote events in your demo solution. Do you have plans to allow the proxy to publish non-local events? (presumably through signalr?)

**Comment by AndersMalmgren** [comment]
Hi, no thats not on the roadmap currently. You can roll your own SignalR hub, it will use the same connection as our library so it will not introduce more strain on the server. 

I'm curious whats the usecase of just fire an event without going through some kind of backend domain (Like save something to database etc)?

**Comment by oising** [comment]
Well, if you wanted a kind of peer-to-peer trigger. If I had a couple of web clients - say, thick html offline/service worker style, and one wanted to notify the rest that something has changed, it'd be nice to be able to broadcast to other clients directly instead of telling the server to do it indirectly.
