### ISSUE TITLE
VersionIfo.cd is missing

### ISSUE THREAD

**Issue by Guson** [AndersMalmgren/SignalR.EventAggregatorProxy#28]
Hi Anders!
I'm interested to use the subscribe feature in your EventAggregatorProxy, will suite our project nicely.

Looking att the code I noticed that `VersionInfo.cs` is missing.

Do you planing any new release of the library? The samples is to old, and are not easy to compile.
/Jonas

**Comment by AndersMalmgren** [comment]
Hi, I have plans of moving to Core but right now I don't have a client that needs it so I haven't done it. You can use the nuget packages, or if you want to build yourself run the /.build/create_nuget_package.cmd

**Comment by AndersMalmgren** [comment]
Demo project used old version of event aggregator. Pull and you can run the demo project now. I just tested with VS2017

**Comment by Guson** [comment]
Hi, thanks for the information. Running the build script, works nicely, and the `VersionInfo.cs` files was created. Build the `SignalR.EventAggregatorProxy` works. I'll test the demo again, use 2017.
Thanks Jonas
